version: 0.2

run-as:

env:
  shell: shell-tag
  variables:
    key: "value"
    key: "value"
  parameter-store:
    key: "value"
    key: "value"
  exported-variables:
    - variable
    - variable
  secrets-manager:
    key: secret-id:json-key:version-stage:version-id
  git-credential-helper: no

proxy:
  upload-artifacts: no
  logs: no

batch:
  fast-fail: false | true
  # build-list:
  # build-matrix:
  # build-graph:
        
phases:
  install:
    run-as: 
    on-failure: ABORT 
    runtime-versions:
      runtime: version
      runtime: version
    commands:
      - command
      - command
    finally:
      - command
      - command
  pre_build:
    run-as:
    on-failure: ABORT
    commands:
      - command
      - command
    finally:
      - command
      - command
  build:
    run-as:
    on-failure: ABORT
    commands:
      - command
      - command
    finally:
      - command
      - command
  post_build:
    run-as:
    on-failure: ABORT
    commands:
      - command
      - command
    finally:
      - command
      - command
reports:
  report-group-name-or-arn:
    files:
      - location
      - location
    base-directory: location
    discard-paths: no
    file-format: report-format
artifacts:
  files:
    - location
    - location
  name: artifact-name
  discard-paths: no
  base-directory: location
  exclude-paths: excluded paths
  enable-symlinks: no
  s3-prefix: prefix
  secondary-artifacts:
    artifactIdentifier:
      files:
        - location
        - location
      name: secondary-artifact-name
      discard-paths: no
      base-directory: location
    artifactIdentifier:
      files:
        - location
        - location
      discard-paths: no
      base-directory: location
cache:
  paths:
    - path
    - path